#!/bin/sh

CREATION_DATE="$(date +'%s')000"

JSON_VARS='window.egeo_demo.CREATION_DATE = "'${CREATION_DATE}'";'
printf "${JSON_VARS}\n">> /var/www/html/assets/vars.js

printf "Starting nginx... Egeo Starter should running...\n * App port: 9502\n"
nginx

echo "Pulling log"
tail -f  /var/log/nginx/access.log
